# Generated by Django 6.0.4 on 2026-09-23 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chitwan Multi-Brand AC Workshop', max_length=150)),
                ('tagline', models.CharField(default='Reliable Multi-Brand AC Servicing & Spare Parts', max_length=200)),
                ('owner_name', models.CharField(default='Workshop Owner', max_length=100)),
                ('phone', models.CharField(default='9855012345', max_length=30)),
                ('alt_phone', models.CharField(blank=True, default='056-520123', max_length=30)),
                ('email', models.EmailField(blank=True, default='workshop@chitwanac.com', max_length=254)),
                ('address', models.CharField(default='Bharatpur-10, Chitwan, Nepal', max_length=255)),
                ('pan_number', models.CharField(blank=True, default='304859201', max_length=50)),
                ('currency_symbol', models.CharField(default='Rs.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('JOB_UPDATE', 'Job Status/Work Update'), ('STOCK_UPDATE', 'Inventory/Stock Change'), ('PAYMENT', 'Payment Record'), ('SYSTEM', 'System/Settings Change'), ('STAFF', 'Staff Activity')], default='JOB_UPDATE', max_length=30)),
                ('job_reference', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('ESEWA', 'eSewa QR'), ('FONEPAY', 'Fonepay QR'), ('BANK', 'Bank QR'), ('OTHER', 'Other Payment QR')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment_qrs/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_qrs', to='core.business')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
