# Generated by Django 6.0.4 on 2026-09-23 19:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_type', models.CharField(choices=[('Split AC', 'Split AC (Inverter / Non-Inverter)'), ('Window AC', 'Window AC'), ('Cassette AC', 'Cassette / Ceiling AC'), ('Multi-Split', 'Multi-Split AC System'), ('Tower AC', 'Tower / Floor Standing AC'), ('Ductable', 'Ductable Split AC')], default='Split AC', max_length=40)),
                ('capacity', models.CharField(choices=[('0.75 Ton', '0.75 Ton'), ('1.0 Ton', '1.0 Ton'), ('1.5 Ton', '1.5 Ton'), ('2.0 Ton', '2.0 Ton'), ('2.5 Ton', '2.5 Ton'), ('3.0 Ton', '3.0 Ton'), ('4.0+ Ton', '4.0+ Ton (Commercial)')], default='1.5 Ton', max_length=30)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location_notes', models.CharField(blank=True, help_text='e.g. Master Bedroom, Office Floor 2', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_units', to='inventory.brand')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_units', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('ac_brand_name', models.CharField(blank=True, max_length=80)),
                ('ac_type_name', models.CharField(blank=True, default='Split AC', max_length=50)),
                ('ac_capacity_name', models.CharField(blank=True, default='1.5 Ton', max_length=30)),
                ('service_type', models.CharField(choices=[('AC Not Cooling', 'AC Not Cooling / Low Cooling'), ('General Service', 'General Service / Wet Cleaning'), ('Gas Charging', 'Refrigerant Leak & Gas Charging'), ('PCB Replacement', 'PCB Diagnostic & Replacement'), ('Capacitor Replacement', 'Capacitor Replacement / Motor Humming'), ('Compressor Issue', 'Compressor Tripping / Replacement'), ('Water Leakage', 'Water Dripping / Drain Blockage'), ('Installation', 'AC Installation / Shift'), ('Electrical Issue', 'Wiring / Sensor / Contactor Fault'), ('Other Repair', 'Other AC Repair')], default='AC Not Cooling', max_length=60)),
                ('complaint', models.TextField(help_text='Customer reported issue or inspection requirements')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_FOR_PARTS', 'Waiting for Parts'), ('COMPLETED', 'Completed'), ('PAYMENT_PENDING', 'Payment Pending'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=25)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('technician_notes', models.TextField(blank=True)),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('parts_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ESEWA', 'eSewa'), ('FONEPAY', 'Fonepay'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ac_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='services.acunit')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_jobs', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_jobs', to='customers.customer')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_usages', to='inventory.inventoryitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='services.servicejob')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='services.servicejob')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
