# Generated by Django 6.0.4 on 2026-09-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_service_job'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='inventory.brand'),
        ),
    ]
