# Generated by Django 6.0.4 on 2026-09-25 08:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_amount_paid_invoice_dealer_claim_amount_and_more'),
        ('services', '0002_servicejob_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='acunit',
            name='appliance_type',
            field=models.CharField(choices=[('AC', 'Air Conditioner (AC)'), ('REFRIGERATOR', 'Refrigerator / Fridge'), ('WASHING_MACHINE', 'Washing Machine'), ('COOLER', 'Air Cooler')], default='AC', max_length=30),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='appliance_type',
            field=models.CharField(choices=[('AC', 'Air Conditioner (AC)'), ('REFRIGERATOR', 'Refrigerator / Fridge'), ('WASHING_MACHINE', 'Washing Machine'), ('COOLER', 'Air Cooler')], db_index=True, default='AC', max_length=30),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='cancel_reason',
            field=models.CharField(blank=True, help_text="e.g. 'He did not send him machine', 'Customer cancelled'", max_length=255),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='dealer_claim_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='dealer_claim_status',
            field=models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to Dealer'), ('SETTLED', 'Settled / Reimbursed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='is_warranty',
            field=models.BooleanField(db_index=True, default=False, help_text='True if work is covered under Brand / Dealer warranty (WTY)'),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='job_type',
            field=models.CharField(choices=[('INSTALLATION', 'Installation (Wall mount/piping)'), ('UNINSTALLATION', 'Uninstallation / Shifting'), ('GENERAL_SERVICE', 'General Service / Maintenance (SVC only)'), ('REPAIR', 'Repair & Spare Part Replacement'), ('DEMO', 'Demo / Inspection'), ('REPEAT_COMPLAINT', 'Repeat Complaint / Warranty Rework')], db_index=True, default='GENERAL_SERVICE', max_length=30),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='warranty_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_jobs', to='billing.dealer'),
        ),
        migrations.AlterField(
            model_name='acunit',
            name='ac_type',
            field=models.CharField(choices=[('Split AC', 'Split AC (Inverter / Non-Inverter)'), ('Window AC', 'Window AC'), ('Cassette AC', 'Cassette / Ceiling AC'), ('Multi-Split', 'Multi-Split AC System'), ('Tower AC', 'Tower / Floor Standing AC'), ('Ductable', 'Ductable Split AC'), ('Single Door', 'Single Door Refrigerator'), ('Double Door', 'Double Door / Frost-Free Refrigerator'), ('Deep Freezer', 'Deep Freezer / Chest Freezer'), ('Front Load', 'Front Load Washing Machine'), ('Top Load', 'Top Load Fully-Automatic Washing Machine'), ('Semi Auto', 'Semi-Automatic Twin Tub Washing Machine'), ('Desert Cooler', 'Desert Air Cooler'), ('Personal Cooler', 'Personal / Room Cooler'), ('Other Unit', 'Other Appliance')], default='Split AC', max_length=40),
        ),
        migrations.AlterField(
            model_name='acunit',
            name='capacity',
            field=models.CharField(choices=[('0.75 Ton', '0.75 Ton'), ('1.0 Ton', '1.0 Ton'), ('1.5 Ton', '1.5 Ton'), ('2.0 Ton', '2.0 Ton'), ('2.5 Ton', '2.5 Ton'), ('3.0 Ton', '3.0 Ton'), ('4.0+ Ton', '4.0+ Ton (Commercial)'), ('180-220 Ltr', '180–220 Liters (Ref)'), ('250-350 Ltr', '250–350 Liters (Ref)'), ('400+ Ltr', '400+ Liters (Deep Freezer)'), ('6.0-7.5 Kg', '6.0–7.5 Kg (WM)'), ('8.0-10 Kg', '8.0–10 Kg (WM)'), ('40-60 Ltr', '40–60 Liters (Cooler)'), ('Standard', 'Standard Size')], default='1.5 Ton', max_length=30),
        ),
        migrations.AlterField(
            model_name='acunit',
            name='location_notes',
            field=models.CharField(blank=True, help_text='e.g. Kitchen, Master Bedroom, Balcony', max_length=150),
        ),
        migrations.AlterField(
            model_name='servicejob',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ESEWA', 'eSewa'), ('FONEPAY', 'Fonepay'), ('BANK', 'Bank Transfer'), ('DEALER_CLAIM', 'Dealer Claim Reimbursed'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicejob',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Due (Deuu)'), ('PAID', 'Paid'), ('WARRANTY', 'Warranty Claim (WTY)')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicejob',
            name='service_type',
            field=models.CharField(choices=[('General Service', 'General Service / Cleaning (SVC only)'), ('Gas Charging', 'Refrigerant Leak & Gas Charging'), ('No Cooling', 'No Cooling / Poor Cooling'), ('Not Working', 'Not Working / Machine Dead'), ('Motor or PCB', 'Motor or PCB Failure'), ('Relay Overload', 'Relay / Overload Replacement'), ('Compressor Issue', 'Compressor Tripping / Replacement'), ('Capacitor Replacement', 'Capacitor Replacement / Motor Humming'), ('Drain & Gasket', 'Drain Pipe Blockage / Gasket Repair'), ('Water Leakage', 'Water Dripping / Leakage'), ('Installation', 'Installation / Wall Mount'), ('Uninstallation', 'Uninstallation'), ('Other Repair', 'Other Repair')], default='No Cooling', max_length=60),
        ),
        migrations.AlterField(
            model_name='servicejob',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_FOR_PARTS', 'Waiting for Parts'), ('COMPLETED', 'Completed'), ('PAYMENT_PENDING', 'Payment Pending (Due)'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled / Aborted')], db_index=True, default='NEW', max_length=25),
        ),
    ]
