# Generated by Django 6.0.4 on 2026-09-23 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / Owner'), ('TECHNICIAN', 'Technician / Staff')], default='TECHNICIAN', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, default='Bharatpur, Chitwan', max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('WORKING', 'Working'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', max_length=20)),
                ('specialization', models.CharField(blank=True, default='Multi-Brand Inverter & Split AC', max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
    ]
