# Generated by Django 6.0.4 on 2026-09-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_service_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='appliance_type',
            field=models.CharField(choices=[('ALL', 'All / Common Appliances'), ('AC', 'Air Conditioner (AC)'), ('REFRIGERATOR', 'Refrigerator / Fridge'), ('WASHING_MACHINE', 'Washing Machine'), ('COOLER', 'Air Cooler')], db_index=True, default='ALL', max_length=30),
        ),
    ]
