# Generated by Django 6.0.4 on 2026-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
